Repository UEK-i-team/team-homepage, pull requests merged in 2024-03, with the labels that each got.

#38 feature: created project-view subpage
  src/components/ItemTile/ItemTile.js
  src/components/OurProjects/OurProjects.js
  src/pages/projectView.js
Labels: ready to review

#36 feature: change language button
  src/assets/svgs/globe.svg
  src/components/Navbar/Navbar.js
  src/components/Navbar/Navbar.module.scss
  src/i18n/enTranslation.js
  src/i18n/plTranslation.js
Labels: ready to review

#45 fix: repair tabbing and outline highlight
  src/assets/styles/baseStyles.scss
  src/assets/styles/theme.scss
  src/components/Footer/Footer.module.scss
  src/components/SidebarMenu/SidebarMenu.js
  src/components/SidebarMenu/SidebarMenu.module.scss
Labels: fixes needed

#43 fix: size changes
  src/assets/svgs/facebook.svg
  src/components/Footer/Footer.module.scss
  src/components/SidebarMenu/SidebarMenu.module.scss
Labels: review in progress

#48 functional navbar indication
  src/assets/styles/theme.scss
  src/components/Navbar/Navbar.js
  src/components/Navbar/Navbar.module.scss
Labels: fixes needed
